<?php
//-----------------------------------------------------------

/**
 * Переменные, связанные с базой данных
 * 
 */

//Аутентификация 
$DBAddress = 'localhost';
$DBUser = 'root';
$DBPassword = '';

//Названия таблиц
define("DB", "webindex", true);
define("TOPICSTABLE", "dmoz_topics", true);
define("SITESTABLE","dmoz_sites",true);
define("TEMPTOPICSTABLE", "temp_dmoz_topics", true);
//-----------------------------------------------------------


?>