######################################################################
# Automatically generated by qmake (3.0) ?? ???. 14 15:58:18 2015
######################################################################

TEMPLATE = app
TARGET = robot
INCLUDEPATH += .

# Input
HEADERS += main_window.h planet.h robot.h robot_firmware.h
SOURCES += main.cpp main_window.cpp planet.cpp robot.cpp robot_firmware.cpp

QT += widgets
QMAKE_CXXFLAGS += -std=c++11
RESOURCES += robot.qrc
