######################################################################
# Automatically generated by qmake (3.0) ?? ???. 11 15:59:38 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = tic_tac_toe
INCLUDEPATH += .

# Input
HEADERS += main_window.h cell.h
SOURCES += main.cpp main_window.cpp cell.cpp
QMAKE_CXXFLAGS += -std=c++11
RESOURCES += tic_tac_toe.qrc