//---------------------------------------------------------------------------

#ifndef calculusH
#define calculusH
#include "interpretator.h"
#include <Buttons.hpp>
#include <Classes.hpp>
#include <ComCtrls.hpp>
#include <Controls.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Grids.hpp>
#include <Menus.hpp>
#include <StdCtrls.hpp>
#include "InfoForm.cpp"
#include "Author.cpp"
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Buttons.hpp>
#include <ComCtrls.hpp>
#include <Grids.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Menus.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
   TPageControl *PageControl1;
   TTabSheet *TabSheet1;
   TLabel *Label1;
   TGroupBox *GroupBox1;
   TEdit *Edit1;
   TBitBtn *BitBtn1;
   TGroupBox *GroupBox2;
   TEdit *Edit2;
   TGroupBox *GroupBox3;
   TEdit *Edit3;
   TGroupBox *GroupBox4;
   TEdit *Edit4;
   TGroupBox *GroupBox5;
   TEdit *Edit5;
   TBitBtn *BitBtn2;
   TGroupBox *GroupBox6;
   TRadioButton *RadioButton1;
   TRadioButton *RadioButton2;
   TRadioButton *RadioButton3;
   TTabSheet *TabSheet2;
   TPageControl *PageControl2;
   TTabSheet *TabSheet3;
   TGroupBox *GroupBox7;
   TStringGrid *StringGrid1;
   TBitBtn *BitBtn3;
   TGroupBox *GroupBox8;
   TLabel *Label2;
   TLabel *Label3;
   TEdit *Edit6;
   TEdit *Edit7;
   TBitBtn *BitBtn4;
   TGroupBox *GroupBox9;
   TLabel *Label8;
   TEdit *Edit11;
   TGroupBox *GroupBox10;
   TLabel *Label4;
   TGroupBox *GroupBox11;
   TRadioButton *RadioButton4;
   TRadioButton *RadioButton5;
   TRadioButton *RadioButton6;
   TGroupBox *GroupBox12;
   TLabel *Label5;
   TLabel *Label6;
   TEdit *Edit8;
   TEdit *Edit9;
   TGroupBox *GroupBox13;
   TLabel *Label7;
   TEdit *Edit10;
   TTabSheet *TabSheet4;
   TGroupBox *GroupBox14;
   TStringGrid *StringGrid2;
   TGroupBox *GroupBox15;
   TLabel *Label9;
   TEdit *Edit12;
   TGroupBox *GroupBox16;
   TLabel *Label10;
   TLabel *Label11;
   TEdit *Edit13;
   TEdit *Edit14;
   TGroupBox *GroupBox17;
   TRadioButton *RadioButton7;
   TRadioButton *RadioButton8;
   TRadioButton *RadioButton9;
   TGroupBox *GroupBox18;
   TLabel *Label12;
   TEdit *Edit15;
   TGroupBox *GroupBox19;
   TLabel *Label13;
   TLabel *Label14;
   TLabel *Label15;
   TLabel *Label16;
   TLabel *Label17;
   TLabel *Label18;
   TLabel *Label19;
   TLabel *Label20;
   TGroupBox *GroupBox20;
   TLabel *Label21;
   TLabel *Label22;
   TEdit *Edit16;
   TEdit *Edit17;
   TBitBtn *BitBtn5;
   TBitBtn *BitBtn6;
   TTabSheet *TabSheet9;
   TGroupBox *GroupBox21;
   TStringGrid *StringGrid3;
   TGroupBox *GroupBox22;
   TLabel *Label23;
   TEdit *Edit18;
   TGroupBox *GroupBox23;
   TLabel *Label24;
   TEdit *Edit19;
   TGroupBox *GroupBox24;
   TLabel *Label25;
   TLabel *Label26;
   TLabel *Label27;
   TLabel *Label28;
   TLabel *Label29;
   TGroupBox *GroupBox25;
   TLabel *Label32;
   TEdit *Edit22;
   TGroupBox *GroupBox26;
   TLabel *Label30;
   TLabel *Label31;
   TEdit *Edit20;
   TEdit *Edit21;
   TGroupBox *GroupBox27;
   TRadioButton *RadioButton10;
   TRadioButton *RadioButton11;
   TRadioButton *RadioButton12;
   TGroupBox *GroupBox28;
   TLabel *Label34;
   TEdit *Edit24;
   TBitBtn *BitBtn7;
   TBitBtn *BitBtn8;
   TTabSheet *TabSheet5;
   TPageControl *PageControl3;
   TTabSheet *TabSheet10;
   TGroupBox *GroupBox29;
   TStringGrid *StringGrid4;
   TGroupBox *GroupBox30;
   TLabel *Label33;
   TEdit *Edit23;
   TGroupBox *GroupBox31;
   TLabel *Label35;
   TGroupBox *GroupBox32;
   TLabel *Label38;
   TLabel *Label39;
   TEdit *Edit27;
   TEdit *Edit28;
   TGroupBox *GroupBox33;
   TLabel *Label36;
   TLabel *Label37;
   TEdit *Edit25;
   TEdit *Edit26;
   TGroupBox *GroupBox34;
   TRadioButton *RadioButton13;
   TRadioButton *RadioButton14;
   TRadioButton *RadioButton15;
   TGroupBox *GroupBox35;
   TLabel *Label40;
   TEdit *Edit29;
   TBitBtn *BitBtn9;
   TBitBtn *BitBtn10;
   TTabSheet *TabSheet11;
   TGroupBox *GroupBox36;
   TStringGrid *StringGrid5;
   TGroupBox *GroupBox37;
   TLabel *Label41;
   TLabel *Label42;
   TEdit *Edit30;
   TEdit *Edit31;
   TGroupBox *GroupBox38;
   TLabel *Label43;
   TLabel *Label44;
   TEdit *Edit32;
   TEdit *Edit33;
   TGroupBox *GroupBox39;
   TLabel *Label45;
   TEdit *Edit34;
   TBitBtn *BitBtn11;
   TBitBtn *BitBtn12;
   TGroupBox *GroupBox40;
   TRadioButton *RadioButton16;
   TRadioButton *RadioButton17;
   TRadioButton *RadioButton18;
   TGroupBox *GroupBox41;
   TLabel *Label46;
   TEdit *Edit35;
   TTabSheet *TabSheet12;
   TGroupBox *GroupBox42;
   TStringGrid *StringGrid6;
   TGroupBox *GroupBox44;
   TLabel *Label51;
   TEdit *Edit38;
   TGroupBox *GroupBox45;
   TLabel *Label50;
   TEdit *Edit37;
   TGroupBox *GroupBox46;
   TLabel *Label49;
   TEdit *Edit36;
   TGroupBox *GroupBox47;
   TLabel *Label47;
   TLabel *Label48;
   TEdit *Edit39;
   TEdit *Edit40;
   TGroupBox *GroupBox43;
   TLabel *Label52;
   TEdit *Edit41;
   TGroupBox *GroupBox48;
   TEdit *Edit42;
   TBitBtn *BitBtn13;
   TBitBtn *BitBtn14;
   TGroupBox *GroupBox49;
   TRadioButton *RadioButton19;
   TRadioButton *RadioButton20;
   TRadioButton *RadioButton21;
   TTabSheet *TabSheet7;
   TPageControl *PageControl5;
   TTabSheet *TabSheet16;
   TGroupBox *GroupBox68;
   TLabel *Label91;
   TEdit *Edit61;
   TGroupBox *GroupBox69;
   TLabel *Label92;
   TLabel *Label93;
   TEdit *Edit62;
   TEdit *Edit63;
   TGroupBox *GroupBox70;
   TLabel *Label94;
   TEdit *Edit64;
   TGroupBox *GroupBox71;
   TRadioButton *RadioButton31;
   TRadioButton *RadioButton32;
   TRadioButton *RadioButton33;
   TGroupBox *GroupBox72;
   TBitBtn *BitBtn21;
   TBitBtn *BitBtn22;
   TGroupBox *GroupBox74;
   TEdit *Edit65;
   TGroupBox *GroupBox75;
   TEdit *Edit66;
   TGroupBox *GroupBox73;
   TRadioButton *RadioButton34;
   TRadioButton *RadioButton35;
   TRadioButton *RadioButton36;
   TTabSheet *TabSheet17;
   TGroupBox *GroupBox76;
   TLabel *Label95;
   TEdit *Edit67;
   TGroupBox *GroupBox77;
   TLabel *Label96;
   TLabel *Label97;
   TEdit *Edit68;
   TEdit *Edit69;
   TGroupBox *GroupBox78;
   TRadioButton *RadioButton37;
   TRadioButton *RadioButton38;
   TRadioButton *RadioButton39;
   TGroupBox *GroupBox79;
   TGroupBox *GroupBox80;
   TEdit *Edit70;
   TGroupBox *GroupBox81;
   TEdit *Edit71;
   TBitBtn *BitBtn23;
   TBitBtn *BitBtn24;
   TGroupBox *GroupBox82;
   TLabel *Label98;
   TEdit *Edit72;
   TGroupBox *GroupBox83;
   TImage *Image1;
   TTabSheet *TabSheet18;
   TGroupBox *GroupBox84;
   TLabel *Label99;
   TEdit *Edit73;
   TGroupBox *GroupBox85;
   TLabel *Label100;
   TLabel *Label101;
   TEdit *Edit74;
   TEdit *Edit75;
   TGroupBox *GroupBox86;
   TBitBtn *BitBtn25;
   TBitBtn *BitBtn26;
   TGroupBox *GroupBox87;
   TEdit *Edit76;
   TGroupBox *GroupBox88;
   TEdit *Edit77;
   TGroupBox *GroupBox89;
   TRadioButton *RadioButton40;
   TRadioButton *RadioButton41;
   TRadioButton *RadioButton42;
   TGroupBox *GroupBox90;
   TLabel *Label102;
   TEdit *Edit78;
   TGroupBox *GroupBox92;
   TImage *Image2;
   TTabSheet *TabSheet8;
   TPageControl *PageControl4;
   TTabSheet *TabSheet13;
   TGroupBox *GroupBox50;
   TStringGrid *StringGrid7;
   TGroupBox *GroupBox51;
   TLabel *Label53;
   TEdit *Edit43;
   TGroupBox *GroupBox52;
   TLabel *Label54;
   TLabel *Label55;
   TEdit *Edit44;
   TEdit *Edit45;
   TGroupBox *GroupBox53;
   TLabel *Label56;
   TLabel *Label57;
   TLabel *Label59;
   TEdit *Edit46;
   TEdit *Edit47;
   TEdit *Edit48;
   TGroupBox *GroupBox54;
   TRadioButton *RadioButton22;
   TRadioButton *RadioButton23;
   TRadioButton *RadioButton24;
   TGroupBox *GroupBox55;
   TLabel *Label58;
   TLabel *Label60;
   TBitBtn *BitBtn15;
   TBitBtn *BitBtn16;
   TTabSheet *TabSheet14;
   TGroupBox *GroupBox56;
   TStringGrid *StringGrid8;
   TGroupBox *GroupBox57;
   TLabel *Label61;
   TEdit *Edit49;
   TGroupBox *GroupBox58;
   TLabel *Label62;
   TLabel *Label63;
   TEdit *Edit50;
   TEdit *Edit51;
   TGroupBox *GroupBox59;
   TRadioButton *RadioButton25;
   TRadioButton *RadioButton26;
   TRadioButton *RadioButton27;
   TGroupBox *GroupBox60;
   TLabel *Label64;
   TLabel *Label65;
   TLabel *Label66;
   TEdit *Edit52;
   TEdit *Edit53;
   TEdit *Edit54;
   TBitBtn *BitBtn17;
   TBitBtn *BitBtn18;
   TGroupBox *GroupBox61;
   TLabel *Label67;
   TLabel *Label68;
   TLabel *Label69;
   TLabel *Label70;
   TLabel *Label71;
   TTabSheet *TabSheet15;
   TGroupBox *GroupBox62;
   TStringGrid *StringGrid9;
   TGroupBox *GroupBox63;
   TLabel *Label72;
   TEdit *Edit55;
   TGroupBox *GroupBox64;
   TLabel *Label73;
   TLabel *Label74;
   TEdit *Edit56;
   TEdit *Edit57;
   TGroupBox *GroupBox65;
   TLabel *Label75;
   TLabel *Label76;
   TLabel *Label77;
   TEdit *Edit58;
   TEdit *Edit59;
   TEdit *Edit60;
   TGroupBox *GroupBox66;
   TRadioButton *RadioButton28;
   TRadioButton *RadioButton29;
   TRadioButton *RadioButton30;
   TBitBtn *BitBtn19;
   TBitBtn *BitBtn20;
   TGroupBox *GroupBox67;
   TLabel *Label78;
   TLabel *Label79;
   TLabel *Label80;
   TLabel *Label81;
   TLabel *Label82;
   TLabel *Label83;
   TLabel *Label84;
   TLabel *Label85;
   TLabel *Label86;
   TLabel *Label87;
   TLabel *Label88;
   TLabel *Label89;
   TLabel *Label90;
   TMainMenu *MainMenu1;
   TMenuItem *Help1;
   TMenuItem *Information1;
   TMenuItem *About1;
   void __fastcall FormCreate(TObject *Sender);
   void __fastcall BitBtn1Click(TObject *Sender);
   void __fastcall Edit5KeyPress(TObject *Sender, char &Key);
   void __fastcall Edit1KeyPress(TObject *Sender, char &Key);
   void __fastcall Edit2KeyPress(TObject *Sender, char &Key);
   void __fastcall BitBtn2Click(TObject *Sender);
   void __fastcall BitBtn3Click(TObject *Sender);
   void __fastcall Edit9KeyPress(TObject *Sender, char &Key);
   void __fastcall Edit10KeyPress(TObject *Sender, char &Key);
   void __fastcall BitBtn5Click(TObject *Sender);
   void __fastcall BitBtn7Click(TObject *Sender);
   void __fastcall BitBtn11Click(TObject *Sender);
   void __fastcall BitBtn13Click(TObject *Sender);
   void __fastcall Edit46KeyPress(TObject *Sender, char &Key);
   void __fastcall Edit44Change(TObject *Sender);
   void __fastcall BitBtn15Click(TObject *Sender);
   void __fastcall BitBtn9Click(TObject *Sender);
   void __fastcall BitBtn17Click(TObject *Sender);
   void __fastcall Edit50Change(TObject *Sender);
   void __fastcall Edit56Change(TObject *Sender);
   void __fastcall BitBtn19Click(TObject *Sender);
   void __fastcall BitBtn21Click(TObject *Sender);
   void __fastcall BitBtn23Click(TObject *Sender);
   void __fastcall BitBtn25Click(TObject *Sender);
   void __fastcall Edit1Change(TObject *Sender);
   void __fastcall Information1Click(TObject *Sender);
   void __fastcall About1Click(TObject *Sender);
   void __fastcall Edit47Change(TObject *Sender);
   void __fastcall Edit53Change(TObject *Sender);
   void __fastcall Edit59Change(TObject *Sender);
private:	// User declarations
public:		// User declarations
   __fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
