######################################################################
# Automatically generated by qmake (3.0) ?? ???. 14 15:58:18 2015
######################################################################

TEMPLATE = app
TARGET = koch_snowflake
INCLUDEPATH += .

# Input
HEADERS += main_window.h koch_snowflake_canvas.h
SOURCES += main.cpp main_window.cpp koch_snowflake_canvas.cpp

QT += widgets
QMAKE_CXXFLAGS += -std=c++11
