//---------------------------------------------------------------------------
#ifndef Windows_XP_Registry_CodeH
#define Windows_XP_Registry_CodeH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include "Classes\\Element.h"
#include <Registry.hpp>
#include <ComCtrls.hpp>
#include <Buttons.hpp>
#include <ExtCtrls.hpp>
#include "Forms\\InformationForm\\FormParametr.h"
#include "Forms\\SplashForm\\SplashForm.h"
#include <Menus.hpp>
//---------------------------------------------------------------------------
class TWindows_XP_Registry_Form : public TForm
{
__published:	// IDE-managed Components
   TPageControl *Control_Panel_Pages;
   TTabSheet *Memory;
   TGroupBox *DisablePagingExecutiveHelp;
   TPanel *Panel9;
   TRadioButton *RadioButton13;
   TRadioButton *RadioButton14;
   TBitBtn *DisablePagingExecutiveSave;
   TBitBtn *DisablePagingExecutiveRefresh;
   TGroupBox *LargeSystemCacheHelp;
   TPanel *Panel10;
   TRadioButton *RadioButton15;
   TRadioButton *RadioButton16;
   TBitBtn *LargeSystemCacheSave;
   TBitBtn *LargeSystemCacheRefresh;
   TGroupBox *IOPageLockLimitHelp;
   TPanel *Panel11;
   TGroupBox *GroupBox14;
   TEdit *Edit3;
   TBitBtn *IOPageLockLimitSave;
   TBitBtn *IOPageLockLimitRefresh;
   TGroupBox *ClearPageFileAtShutdownHelp;
   TPanel *Panel12;
   TRadioButton *RadioButton17;
   TRadioButton *RadioButton18;
   TBitBtn *ClearPageFileAtShutdownSave;
   TBitBtn *ClearPageFileAtShutdownRefresh;
   TTabSheet *Explorer;
   TGroupBox *NoLowDiskSpaceChecksHelp;
   TPanel *Panel4;
   TRadioButton *RadioButton5;
   TRadioButton *RadioButton6;
   TBitBtn *NoLowDiskSpaceChecksSave;
   TBitBtn *NoLowDiskSpaceChecksRefresh;
   TGroupBox *FullScreenHelp;
   TPanel *Panel19;
   TRadioButton *RadioButton33;
   TRadioButton *RadioButton34;
   TBitBtn *FullScreenSave;
   TBitBtn *FullScreenRefresh;
   TTabSheet *Acceleration;
   TGroupBox *WaitToKillServiceTimeOutHelp;
   TPanel *Panel3;
   TGroupBox *GroupBox3;
   TEdit *Edit1;
   TBitBtn *BitBtn5;
   TBitBtn *BitBtn6;
   TGroupBox *AutoRunHelp;
   TPanel *Panel1;
   TRadioButton *RadioButton1;
   TRadioButton *RadioButton2;
   TBitBtn *AutoRunSave;
   TBitBtn *AutoRunRefresh;
   TPanel *Panel6;
   TRadioButton *RadioButton9;
   TRadioButton *RadioButton10;
   TBitBtn *NtfsDisableLastAccessUpdateSave;
   TBitBtn *NtfsDisableLastAccessUpdateRefresh;
   TGroupBox *NtfsMftZoneReservationHelp;
   TPanel *Panel18;
   TRadioButton *RadioButton29;
   TRadioButton *RadioButton30;
   TRadioButton *RadioButton31;
   TRadioButton *RadioButton32;
   TBitBtn *NtfsMftZoneReservationSave;
   TBitBtn *NtfsMftZoneReservationRefresh;
   TGroupBox *NtfsDisable8dot3NameCreationHelp;
   TPanel *Panel20;
   TRadioButton *RadioButton35;
   TRadioButton *RadioButton36;
   TBitBtn *NtfsDisable8dot3NameCreationSave;
   TBitBtn *NtfsDisable8dot3NameCreationRefresh;
   TTabSheet *Security;
   TGroupBox *ScreenSaveActiveHelp;
   TPanel *Panel13;
   TRadioButton *RadioButton19;
   TRadioButton *RadioButton20;
   TBitBtn *ScreenSaveActiveSave;
   TBitBtn *ScreenSaveActiveRefresh;
   TGroupBox *DontDisplayLastUserNameHelp;
   TPanel *Panel14;
   TRadioButton *RadioButton21;
   TRadioButton *RadioButton22;
   TBitBtn *DontDisplayLastUserNameSave;
   TBitBtn *DontDisplayLastUserNameRefresh;
   TPanel *Panel15;
   TRadioButton *RadioButton23;
   TRadioButton *RadioButton24;
   TBitBtn *ClearRecentDocsOnExitSave;
   TBitBtn *ClearRecentDocsOnExitRefresh;
   TGroupBox *restrictanonymousHelp;
   TPanel *Panel16;
   TRadioButton *RadioButton25;
   TRadioButton *RadioButton26;
   TBitBtn *restrictanonymousSave;
   TBitBtn *restrictanonymousRefresh;
   TGroupBox *CrashOnCtrlScrollHelp;
   TPanel *Panel17;
   TRadioButton *RadioButton27;
   TRadioButton *RadioButton28;
   TBitBtn *CrashOnCtrlScrollSave;
   TBitBtn *CrashOnCtrlScrollRefresh;
   TTabSheet *Hardware;
   TGroupBox *EnableUDMA66Help;
   TPanel *Panel21;
   TRadioButton *RadioButton37;
   TRadioButton *RadioButton38;
   TBitBtn *EnableUDMA66Save;
   TBitBtn *EnableUDMA66Refresh;
   TGroupBox *PowerdownAfterShutdownHelp;
   TPanel *Panel22;
   TRadioButton *RadioButton39;
   TRadioButton *RadioButton40;
   TBitBtn *PowerdownAfterShutdownSave;
   TBitBtn *PowerdownAfterShutdownRefresh;
   TTabSheet *Net;
   TGroupBox *HiddenHelp;
   TPanel *Panel24;
   TRadioButton *RadioButton43;
   TRadioButton *RadioButton44;
   TBitBtn *SaveHidden;
   TBitBtn *RefreshHidden;
   TGroupBox *AutoShareWksHelp;
   TPanel *Panel25;
   TRadioButton *RadioButton45;
   TRadioButton *RadioButton46;
   TBitBtn *AutoShareWksSave;
   TBitBtn *AutoShareWksRefresh;
   TGroupBox *AutoShareServerHelp;
   TPanel *Panel26;
   TRadioButton *RadioButton47;
   TRadioButton *RadioButton48;
   TBitBtn *AutoShareServerSave;
   TBitBtn *AutoShareServerRefresh;
   TGroupBox *DeadGWDetectDefaultHelp;
   TPanel *Panel27;
   TRadioButton *RadioButton49;
   TRadioButton *RadioButton50;
   TBitBtn *DeadGWDetectDefaultSave;
   TBitBtn *DeadGWDetectDefaultRefresh;
   TGroupBox *MenuShowDelayHelp;
   TPanel *Panel7;
   TGroupBox *GroupBox9;
   TEdit *Edit2;
   TBitBtn *MenuShowDelaySave;
   TBitBtn *MenuShowDelayRefresh;
   TGroupBox *MinAnimateHelp;
   TPanel *Panel8;
   TRadioButton *RadioButton11;
   TRadioButton *RadioButton12;
   TBitBtn *MinAnimateSave;
   TBitBtn *MinAnimateRefresh;
   TGroupBox *SharedDocumentsHelp;
   TPanel *Panel5;
   TRadioButton *RadioButton7;
   TRadioButton *RadioButton8;
   TBitBtn *SharedDocumentsSave;
   TBitBtn *SharedDocumentsRefresh;
   TGroupBox *NoDesktopHelp;
   TPanel *Panel30;
   TRadioButton *RadioButton55;
   TRadioButton *RadioButton56;
   TBitBtn *NoDesktopSave;
   TBitBtn *NoDesktopRefresh;
   TGroupBox *RecycleBinHelp;
   TPanel *Panel31;
   TRadioButton *RadioButton57;
   TRadioButton *RadioButton58;
   TBitBtn *RecycleBinSave;
   TBitBtn *RecycleBinRefresh;
   TPageControl *ExplorerPages;
   TTabSheet *ExplorerPage1;
   TGroupBox *SFCDisableHelp;
   TPanel *Panel23;
   TRadioButton *RadioButton41;
   TRadioButton *RadioButton42;
   TBitBtn *SFCDisableRefresh;
   TGroupBox *AlwaysUnloadDllHelp;
   TPanel *Panel28;
   TRadioButton *RadioButton51;
   TRadioButton *RadioButton52;
   TBitBtn *AlwaysUnloadDllSave;
   TBitBtn *AlwaysUnloadDllRefresh;
   TGroupBox *AutoDebugerHelp;
   TPanel *Panel2;
   TRadioButton *RadioButton3;
   TRadioButton *RadioButton4;
   TBitBtn *AutoDebugerSave;
   TBitBtn *AutoDebugerRefresh;
   TGroupBox *NtfsDisableLastAccessUpdateHelp;
   TTabSheet *Other;
   TBitBtn *SFCDisableSave;
   TPageControl *AccelerationPages;
   TTabSheet *AccelerationP1;
   TGroupBox *ClearRecentDocsOnExitHelp;
   TGroupBox *RecycleBinRenameHelp;
   TPanel *Panel29;
   TBitBtn *RecycleBinRenameSave;
   TBitBtn *RecycleBinRenameRefresh;
   TGroupBox *GroupBox1;
   TEdit *Edit4;
   TGroupBox *CoolBitsHelp;
   TPanel *Panel32;
   TRadioButton *RadioButton53;
   TRadioButton *RadioButton54;
   TBitBtn *CoolBitsSave;
   TBitBtn *CoolBitsRefresh;
   TTabSheet *AccelerationP2;
   TGroupBox *EnablePrefetcherHelp;
   TPanel *Panel33;
   TRadioButton *RadioButton59;
   TRadioButton *RadioButton60;
   TRadioButton *RadioButton61;
   TRadioButton *RadioButton62;
   TBitBtn *EnablePrefetcherSave;
   TBitBtn *EnablePrefetcherRefresh;
   TGroupBox *BeepHelp;
   TPanel *Panel34;
   TRadioButton *RadioButton63;
   TRadioButton *RadioButton64;
   TBitBtn *BeepSave;
   TBitBtn *BeepRefresh;
   TGroupBox *DisableTaskMgrHelp;
   TPanel *Panel35;
   TRadioButton *RadioButton65;
   TRadioButton *RadioButton66;
   TBitBtn *DisableTaskMgrSave;
   TBitBtn *DisableTaskMgrRefresh;
   TGroupBox *PaintDesktopVersionHelp;
   TPanel *Panel36;
   TRadioButton *RadioButton67;
   TRadioButton *RadioButton68;
   TBitBtn *PaintDesktopVersionSave;
   TBitBtn *PaintDesktopVersionRefresh;
   TGroupBox *ProtectionModeHelp;
   TPanel *Panel37;
   TRadioButton *RadioButton69;
   TRadioButton *RadioButton70;
   TBitBtn *ProtectionModeSave;
   TBitBtn *ProtectionModeRefresh;
   TTabSheet *ExplorerPage2;
   TGroupBox *NoViewContextMenuHelp;
   TPanel *Panel38;
   TRadioButton *RadioButton71;
   TRadioButton *RadioButton72;
   TBitBtn *NoViewContextMenuSave;
   TBitBtn *NoViewContextMenuRefresh;
   TGroupBox *DisableRegistryToolsHelp;
   TPanel *Panel39;
   TRadioButton *RadioButton73;
   TRadioButton *RadioButton74;
   TBitBtn *DisableRegistryToolsSave;
   TBitBtn *DisableRegistryToolsRefresh;
   TGroupBox *InitialKeyboardIndicatorsHelp;
   TPanel *Panel40;
   TRadioButton *RadioButton75;
   TRadioButton *RadioButton76;
   TBitBtn *InitialKeyboardIndicatorsSave;
   TBitBtn *InitialKeyboardIndicatorsRefresh;
   TGroupBox *IPEnableRouterHelp;
   TPanel *Panel41;
   TRadioButton *RadioButton77;
   TRadioButton *RadioButton78;
   TBitBtn *IPEnableRouterSave;
   TBitBtn *IPEnableRouterRefresh;
   TGroupBox *EnableICMPRedirectHelp;
   TPanel *Panel42;
   TRadioButton *RadioButton79;
   TRadioButton *RadioButton80;
   TBitBtn *EnableICMPRedirectSave;
   TBitBtn *EnableICMPRedirectRefresh;
   TGroupBox *EnablePMTUDiscoveryHelp;
   TPanel *Panel43;
   TRadioButton *RadioButton81;
   TRadioButton *RadioButton82;
   TBitBtn *EnablePMTUDiscoverySave;
   TBitBtn *EnablePMTUDiscoveryRefresh;
   TGroupBox *NoNameReleaseOnDemandHelp;
   TPanel *Panel44;
   TRadioButton *RadioButton83;
   TRadioButton *RadioButton84;
   TBitBtn *NoNameReleaseOnDemandSave;
   TBitBtn *NoNameReleaseOnDemandRefresh;
   TPageControl *NetPages;
   TTabSheet *NetPage1;
   TGroupBox *AutoEndTasksHelp;
   TPanel *Panel46;
   TRadioButton *RadioButton87;
   TRadioButton *RadioButton88;
   TBitBtn *AutoEndTasksSave;
   TBitBtn *AutoEndTasksRedresh;
   TGroupBox *WaitToKillAppTimeoutHelp;
   TPanel *Panel47;
   TBitBtn *WaitToKillAppTimeoutSave;
   TBitBtn *WaitToKillAppTimeoutRefresh;
   TGroupBox *GroupBox4;
   TEdit *Edit5;
   TGroupBox *HungAppTimeoutHelp;
   TPanel *Panel48;
   TGroupBox *GroupBox6;
   TEdit *Edit6;
   TBitBtn *HungAppTimeoutSave;
   TBitBtn *HungAppTimeoutRefresh;
   TGroupBox *InitialKeyboardIndicatorsUserHelp;
   TPanel *Panel49;
   TRadioButton *RadioButton89;
   TRadioButton *RadioButton90;
   TBitBtn *InitialKeyboardIndicatorsUserSave;
   TBitBtn *InitialKeyboardIndicatorsUserRefresh;
   TMainMenu *MainMenu1;
   TMenuItem *Help1;
   TMenuItem *Aboutprogram1;
   TMenuItem *About1;
   TGroupBox *GroupBox2;
   TPanel *Panel45;
   TRadioButton *RadioButton85;
   TRadioButton *RadioButton86;
   TBitBtn *BitBtn1;
   TBitBtn *BitBtn2;
   void __fastcall AutoRunSaveClick(TObject *Sender);
   void __fastcall AutoRunRefreshClick(TObject *Sender);
   void __fastcall AutoDebugerSaveClick(TObject *Sender);
   void __fastcall AutoDebugerRefreshClick(TObject *Sender);
   void __fastcall BitBtn5Click(TObject *Sender);
   void __fastcall BitBtn6Click(TObject *Sender);
   void __fastcall NoLowDiskSpaceChecksSaveClick(TObject *Sender);
   void __fastcall NoLowDiskSpaceChecksRefreshClick(TObject *Sender);
   void __fastcall SharedDocumentsSaveClick(TObject *Sender);
   void __fastcall SharedDocumentsRefreshClick(TObject *Sender);
   void __fastcall NtfsDisableLastAccessUpdateSaveClick(TObject *Sender);
   void __fastcall NtfsDisableLastAccessUpdateRefreshClick(TObject *Sender);
   void __fastcall MenuShowDelaySaveClick(TObject *Sender);
   void __fastcall MenuShowDelayRefreshClick(TObject *Sender);
   void __fastcall MinAnimateSaveClick(TObject *Sender);
   void __fastcall MinAnimateRefreshClick(TObject *Sender);
   void __fastcall DisablePagingExecutiveSaveClick(TObject *Sender);
   void __fastcall DisablePagingExecutiveRefreshClick(TObject *Sender);
   void __fastcall LargeSystemCacheSaveClick(TObject *Sender);
   void __fastcall LargeSystemCacheRefreshClick(TObject *Sender);
   void __fastcall IOPageLockLimitSaveClick(TObject *Sender);
   void __fastcall IOPageLockLimitRefreshClick(TObject *Sender);
   void __fastcall ClearPageFileAtShutdownSaveClick(TObject *Sender);
   void __fastcall ClearPageFileAtShutdownRefreshClick(TObject *Sender);
   void __fastcall ScreenSaveActiveSaveClick(TObject *Sender);
   void __fastcall ScreenSaveActiveRefreshClick(TObject *Sender);
   void __fastcall DontDisplayLastUserNameSaveClick(TObject *Sender);
   void __fastcall DontDisplayLastUserNameRefreshClick(TObject *Sender);
   void __fastcall ClearRecentDocsOnExitSaveClick(TObject *Sender);
   void __fastcall ClearRecentDocsOnExitRefreshClick(TObject *Sender);
   void __fastcall restrictanonymousSaveClick(TObject *Sender);
   void __fastcall restrictanonymousRefreshClick(TObject *Sender);
   void __fastcall CrashOnCtrlScrollSaveClick(TObject *Sender);
   void __fastcall CrashOnCtrlScrollRefreshClick(TObject *Sender);
   void __fastcall NtfsMftZoneReservationSaveClick(TObject *Sender);
   void __fastcall NtfsMftZoneReservationRefreshClick(TObject *Sender);
   void __fastcall FullScreenSaveClick(TObject *Sender);
   void __fastcall FullScreenRefreshClick(TObject *Sender);
   void __fastcall NtfsDisable8dot3NameCreationSaveClick(TObject *Sender);
   void __fastcall NtfsDisable8dot3NameCreationRefreshClick(TObject *Sender);
   void __fastcall EnableUDMA66SaveClick(TObject *Sender);
   void __fastcall EnableUDMA66RefreshClick(TObject *Sender);
   void __fastcall PowerdownAfterShutdownSaveClick(TObject *Sender);
   void __fastcall PowerdownAfterShutdownRefreshClick(TObject *Sender);
   void __fastcall BitBtn45Click(TObject *Sender);
   void __fastcall SFCDisableRefreshClick(TObject *Sender);
   void __fastcall DisablePagingExecutiveHelpClick(TObject *Sender);
   void __fastcall LargeSystemCacheHelpClick(TObject *Sender);
   void __fastcall IOPageLockLimitHelpClick(TObject *Sender);
   void __fastcall SharedDocumentsHelpClick(TObject *Sender);
   void __fastcall AutoDebugerHelpClick(TObject *Sender);
   void __fastcall NoLowDiskSpaceChecksHelpClick(TObject *Sender);
   void __fastcall SaveHiddenClick(TObject *Sender);
   void __fastcall RefreshHiddenClick(TObject *Sender);
   void __fastcall HiddenHelpClick(TObject *Sender);
   void __fastcall AutoShareWksSaveClick(TObject *Sender);
   void __fastcall AutoShareWksRefreshClick(TObject *Sender);
   void __fastcall AutoShareWksHelpClick(TObject *Sender);
   void __fastcall AutoShareServerSaveClick(TObject *Sender);
   void __fastcall AutoShareServerRefreshClick(TObject *Sender);
   void __fastcall AutoShareServerHelpClick(TObject *Sender);
   void __fastcall AlwaysUnloadDllSaveClick(TObject *Sender);
   void __fastcall AlwaysUnloadDllRefreshClick(TObject *Sender);
   void __fastcall AlwaysUnloadDllHelpClick(TObject *Sender);
   void __fastcall AutoRunHelpClick(TObject *Sender);
   void __fastcall NoDesktopSaveClick(TObject *Sender);
   void __fastcall NoDesktopRefreshClick(TObject *Sender);
   void __fastcall NoDesktopHelpClick(TObject *Sender);
   void __fastcall RecycleBinSaveClick(TObject *Sender);
   void __fastcall RecycleBinRefreshClick(TObject *Sender);
   void __fastcall RecycleBinHelpClick(TObject *Sender);
   void __fastcall ClearPageFileAtShutdownHelpClick(TObject *Sender);
   void __fastcall FullScreenHelpClick(TObject *Sender);
   void __fastcall PowerdownAfterShutdownHelpClick(TObject *Sender);
   void __fastcall EnableUDMA66HelpClick(TObject *Sender);
   void __fastcall WaitToKillServiceTimeOutHelpClick(TObject *Sender);
   void __fastcall MenuShowDelayHelpClick(TObject *Sender);
   void __fastcall MinAnimateHelpClick(TObject *Sender);
   void __fastcall GroupBox5Click(TObject *Sender);
   void __fastcall SFCDisableHelpClick(TObject *Sender);
   void __fastcall CrashOnCtrlScrollHelpClick(TObject *Sender);
   void __fastcall ScreenSaveActiveHelpClick(TObject *Sender);
   void __fastcall DontDisplayLastUserNameHelpClick(TObject *Sender);
   void __fastcall GroupBox18Click(TObject *Sender);
   void __fastcall restrictanonymousHelpClick(TObject *Sender);
   void __fastcall NtfsDisable8dot3NameCreationHelpClick(TObject *Sender);
   void __fastcall NtfsMftZoneReservationHelpClick(TObject *Sender);
   void __fastcall RecycleBinRenameSaveClick(TObject *Sender);
   void __fastcall RecycleBinRenameRefreshClick(TObject *Sender);
   void __fastcall RecycleBinRenameHelpClick(TObject *Sender);
   void __fastcall CoolBitsSaveClick(TObject *Sender);
   void __fastcall CoolBitsHelpClick(TObject *Sender);
   void __fastcall CoolBitsRefreshClick(TObject *Sender);
   void __fastcall EnablePrefetcherSaveClick(TObject *Sender);
   void __fastcall EnablePrefetcherRefreshClick(TObject *Sender);
   void __fastcall EnablePrefetcherHelpClick(TObject *Sender);
   void __fastcall BeepSaveClick(TObject *Sender);
   void __fastcall BeepRefreshClick(TObject *Sender);
   void __fastcall BeepHelpClick(TObject *Sender);
   void __fastcall DisableTaskMgrSaveClick(TObject *Sender);
   void __fastcall DisableTaskMgrRefreshClick(TObject *Sender);
   void __fastcall DisableTaskMgrHelpClick(TObject *Sender);
   void __fastcall PaintDesktopVersionSaveClick(TObject *Sender);
   void __fastcall PaintDesktopVersionRefreshClick(TObject *Sender);
   void __fastcall PaintDesktopVersionHelpClick(TObject *Sender);
   void __fastcall ProtectionModeSaveClick(TObject *Sender);
   void __fastcall ProtectionModeRefreshClick(TObject *Sender);
   void __fastcall ProtectionModeHelpClick(TObject *Sender);
   void __fastcall NoViewContextMenuSaveClick(TObject *Sender);
   void __fastcall NoViewContextMenuRefreshClick(TObject *Sender);
   void __fastcall NoViewContextMenuHelpClick(TObject *Sender);
   void __fastcall DisableRegistryToolsSaveClick(TObject *Sender);
   void __fastcall DisableRegistryToolsRefreshClick(TObject *Sender);
   void __fastcall DisableRegistryToolsHelpClick(TObject *Sender);
   void __fastcall InitialKeyboardIndicatorsSaveClick(TObject *Sender);
   void __fastcall InitialKeyboardIndicatorsRefreshClick(TObject *Sender);
   void __fastcall InitialKeyboardIndicatorsHelpClick(TObject *Sender);
   void __fastcall IPEnableRouterSaveClick(TObject *Sender);
   void __fastcall IPEnableRouterRefreshClick(TObject *Sender);
   void __fastcall IPEnableRouterHelpClick(TObject *Sender);
   void __fastcall DeadGWDetectDefaultSaveClick(TObject *Sender);
   void __fastcall DeadGWDetectDefaultRefreshClick(TObject *Sender);
   void __fastcall DeadGWDetectDefaultHelpClick(TObject *Sender);
   void __fastcall EnableICMPRedirectSaveClick(TObject *Sender);
   void __fastcall EnableICMPRedirectRefreshClick(TObject *Sender);
   void __fastcall EnableICMPRedirectHelpClick(TObject *Sender);
   void __fastcall EnablePMTUDiscoverySaveClick(TObject *Sender);
   void __fastcall EnablePMTUDiscoveryRefreshClick(TObject *Sender);
   void __fastcall EnablePMTUDiscoveryHelpClick(TObject *Sender);
   void __fastcall NoNameReleaseOnDemandSaveClick(TObject *Sender);
   void __fastcall NoNameReleaseOnDemandRefreshClick(TObject *Sender);
   void __fastcall NoNameReleaseOnDemandHelpClick(TObject *Sender);
   void __fastcall AutoEndTasksSaveClick(TObject *Sender);
   void __fastcall AutoEndTasksRedreshClick(TObject *Sender);
   void __fastcall AutoEndTasksHelpClick(TObject *Sender);
   void __fastcall WaitToKillAppTimeoutSaveClick(TObject *Sender);
   void __fastcall WaitToKillAppTimeoutRefreshClick(TObject *Sender);
   void __fastcall WaitToKillAppTimeoutHelpClick(TObject *Sender);
   void __fastcall HungAppTimeoutSaveClick(TObject *Sender);
   void __fastcall HungAppTimeoutRefreshClick(TObject *Sender);
   void __fastcall HungAppTimeoutHelpClick(TObject *Sender);
   void __fastcall InitialKeyboardIndicatorsUserSaveClick(TObject *Sender);
   void __fastcall InitialKeyboardIndicatorsUserRefreshClick(
          TObject *Sender);
   void __fastcall InitialKeyboardIndicatorsUserHelpClick(TObject *Sender);
   void __fastcall FormCreate(TObject *Sender);
   void __fastcall About1Click(TObject *Sender);
   void __fastcall Aboutprogram1Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
   __fastcall TWindows_XP_Registry_Form(TComponent* Owner);
   void __fastcall SaveValue(TElement);
   void __fastcall RefreshValue(TElement &);
};
//---------------------------------------------------------------------------
extern PACKAGE TWindows_XP_Registry_Form *Windows_XP_Registry_Form;
#endif
